### PR TITLE
Fix regressions in model code and views

### PR DESCRIPTION
**Pull request by phmccarty**
Some code in crash.py expects there to be a named parameter named 'id' for get_new_crash_records(), but the method definition recently renamed that parameter to '_id'. This was resulting in the following exception:

```
TypeError: get_new_crash_records() got an unexpected keyword argument 'id'
```

Also, it appears SQLAlchemy only accepts '==' for filtering on a boolean
field, not 'is'. This was affecting the both guilty processing and multiple views.

### CODE REVIEW

**Review by alexjch — APPROVED** [review]
+1 looks good. PEP8 does not know about SQLAlchemy

**Comment by phmccarty** [comment]
Thanks! Merging
